name: "train-workflow"
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
  
jobs:
  deployment:
    runs-on: self-hosted
    environment: dev
    steps:
      - name: "login"
        uses: azure/login@v3.0.0
        with:
          creds: ${{secrets.AZURE_CREDENTIAL}}
      - name: "checkout"
        uses: actions/checkout@v6
      - name: "submit job(deploy)"
        run: |
          uv sync
          uv run src/train/train-job.py
      - run: echo "job deployed"

      